### PR TITLE
Add option to display changes when using the pipeline step

### PR DESCRIPTION
**Pull request by AnsisMalins**
This code compiles, and I installed it on my Jenkins instance. If it works, I'll know in a day or two when there are builds with changes, so don't merge just yet. In the meantime, let me know if I failed any style guidelines. I don't actually know Java.

### CODE REVIEW

**Comment by AnsisMalins** [comment]
I think I've tested the change sufficiently. Merge whenever.

**Review by KocproZ — CHANGES_REQUESTED** [review]
Looks good. Can you also add the 2 new variables you created in DiscordPipelineStep to [pipeline step config.jelly](https://github.com/AnsisMalins/jenkins-discord/blob/more-pipeline/src/main/resources/nz/co/jammehcow/jenkinsdiscord/DiscordPipelineStep/config.jelly)? It should be pretty easy.

**Comment by AnsisMalins** [comment]
I think I did it, but I have no clue how to test it. Where in Jenkins does this Jelly stuff show up?

**Comment by KocproZ** [comment]
When you go to edit pipeline project at the bottom there should be a link called `pipeline syntax`. It opens a new tab. Then in this opened tab select discordSend from the dropdown.

**Comment by AnsisMalins** [comment]
image

**Comment by KocproZ** [comment]
`Show Changeset` looks good, can you also add the second boolean there (`Enable Artifacts List`)?

**Review by KocproZ — APPROVED** [review]

**Pull request merged**
